export const browserCoreExamples = [
  "supportsquadai browser status",
  "supportsquadai browser start",
  "supportsquadai browser stop",
  "supportsquadai browser tabs",
  "supportsquadai browser open https://example.com",
  "supportsquadai browser focus abcd1234",
  "supportsquadai browser close abcd1234",
  "supportsquadai browser screenshot",
  "supportsquadai browser screenshot --full-page",
  "supportsquadai browser screenshot --ref 12",
  "supportsquadai browser snapshot",
  "supportsquadai browser snapshot --format aria --limit 200",
  "supportsquadai browser snapshot --efficient",
  "supportsquadai browser snapshot --labels",
];

export const browserActionExamples = [
  "supportsquadai browser navigate https://example.com",
  "supportsquadai browser resize 1280 720",
  "supportsquadai browser click 12 --double",
  'supportsquadai browser type 23 "hello" --submit',
  "supportsquadai browser press Enter",
  "supportsquadai browser hover 44",
  "supportsquadai browser drag 10 11",
  "supportsquadai browser select 9 OptionA OptionB",
  "supportsquadai browser upload /tmp/supportsquadai/uploads/file.pdf",
  'supportsquadai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "supportsquadai browser dialog --accept",
  'supportsquadai browser wait --text "Done"',
  "supportsquadai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "supportsquadai browser console --level error",
  "supportsquadai browser pdf",
];
